import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { NextauthProvider } from "@/lib/nextauth-provider";
import { ScrollProvider } from "@/lib/scroll-provider";
import { ThemeProvider } from "@/lib/theme-provider";
import { Toaster } from 'sonner'
import { LoadingProvider } from "@/lib/loading-provider";

const poppins = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500'] });
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextauthProvider>
          <ThemeProvider attribute="class" defaultTheme="system">
            <LoadingProvider>
              <ScrollProvider>
                <Toaster position="bottom-right" expand />
                {children}
              </ScrollProvider>
            </LoadingProvider>
          </ThemeProvider>
        </NextauthProvider>
      </body>
    </html>
  );
}
