import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { NextauthProvider } from "@/lib/nextauth-provider";
import { ScrollProvider } from "@/lib/scroll-provider";

const poppins = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500'] });
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextauthProvider>
          <ScrollProvider>
            {children}
          </ScrollProvider>
        </NextauthProvider>
      </body>
    </html>
  );
}
